### ISSUE TITLE
update SDK and build tool versions after fresh Android Studio install for spring 2017

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/clickcounter-android-java#38]
@ares09x should perform a fresh AS install in mid-January to determine the correct SDK and build tool versions.

@klaeufer can then batch-update all COMP 313/413 course examples consistently.

**Comment by klaeufer** [comment]
I did this today, but let's leave this issue open and check again in mid-January.

**Comment by ares09x** [comment]
Fixed by update on March 9, 2017 (which see).
