### ISSUE TITLE
make sure Robolectric tests run in AS and on the command line

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/clickcounter-android-java#67]
http://stackoverflow.com/questions/26804651/how-to-access-files-from-assets-folder-during-tests-execution
http://stackoverflow.com/questions/29105602/robolectric-tests-running-in-android-studio-but-not-on-the-command-line

**Comment by ares09x** [comment]
fixed by updates on March 9, 2017 (see commit on that date)
